### PR TITLE
Toasts

### PR DESCRIPTION
**Pull request by jeffklassen**
Toasts working and basic toasts configured for most of the use cases.

### CODE REVIEW

**Comment by mnmercer** [comment]
I'm not going to be able to get to this until Sunday, but I'll go through it as soon as I can.

**Comment by BKreisel** [comment]
Addressed  merge conflicts

**Comment by BKreisel** [comment]
screen shot 2017-05-05 at 10 51 24 am

**Comment by jeffklassen** [comment]
Fix it!

**Comment by mnmercer** [comment]
Having trouble getting the application to actually start on this branch. I started MongoDB, ran `npm install`, and then `npm start`, but opening up http://localhost:3030/ got me a blank screen with 404 errors for `vendor.bundle.js` and `bundle.js`.

**Comment by jeffklassen** [comment]
Run npm run webpack

**Comment by mnmercer** [comment]
Do we need a success toast for creating users?

**Comment by jeffklassen** [comment]
@BKreisel I'm not able to reproduce that error. 
@mnmercer 
I'm merging - per @BKreisel's acceptance of this in chat.

**Pull request merged**
