### PR TITLE
Group join

### PR DESCRIPTION
**Pull request by jeffklassen**
The group join form should be complete

### CODE REVIEW

**Comment by BKreisel** [comment]
A few observations:
   - The custom student / couple signups are not implemented (this could possibly be handled in a later pull request ) 
  - The phone numbers don't appear to have any validation.

Otherwise LGTM. Good work!

**Comment by jeffklassen** [comment]
@BKreisel What do you mean about the custom couples sign ups? When the group type is 'Couples' it works:

screen shot 2017-04-30 at 9 22 11 am

**Comment by jeffklassen** [comment]
@BKreisel ah -- I see that if it is 'Married Couples' it does not work. Is that what you are seeing or are you seeing something else?

**Comment by BKreisel** [comment]
@jeffklassen: Ah yes, I did my testing with a "married couples"group. That appears to be the issue.

**Comment by BKreisel** [comment]
Addressed with some ES2016 Array.prototype.includes() magic

**Comment by jeffklassen** [comment]
@BKreisel Man, I really like your solution. We _might_ want to pull that out into its own function. Maybe add this to utils and have a 
```const isCouplyGroup =(group) ={
   return ['Couples, 'Married couples'].includes(group.audienceType);
}```

just so we are not copying logic around and having to maintain that logic in multiple places.

**Comment by jeffklassen** [comment]
Oh.. heh.. you did that!!!!

**Pull request merged**
